# Generated by Django 3.0.2 on 2020-01-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_messages_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='user',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
